import type { Metadata } from 'next'
import './globals.css'
import { inter } from '@/lib/fonts'
import { TrpcProvider } from '@/providers/trpc'

export const metadata: Metadata = {
  title: {
    default: 'Tickets',
    template: 'Tickets | %s'
  },
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <TrpcProvider>{children}</TrpcProvider>
      </body>
    </html>
  )
}
